name: CI

on:
  push:
    branches:
      - master
jobs:
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: 检查架构
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          BUCKET_NAME: lq-open
        run: |
          echo ${{ env.GITHUB_REPOSITORY }}
          echo ${{ env.BUCKET_NAME }}
      - name: 只下载更新的文件
        uses: actions/checkout@v3

      - name: 配置AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Change Files
        id: changed-files
        uses: tj-actions/changed-files@v37
      - name: 定义s3路径
        run: |
          REMOTE_PATH="s3://${{ env.BUCKET_NAME }}/${{ env.GITHUB_REPOSITORY }}/$file"
          echo $REMOTE_PATH
      - name: List adn Upload All Change Files
        run: |
          echo "Actor: ${{ toJson(steps) }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
            aws s3 cp $file "$REMOTE_PATH"
          done
          mkdir aaa

      - name:  List and Delete All Deleted Files
        run: |
            S3_BUCKET=${{ env.BUCKET_NAME }}
            S3_PATH="${{ env.GITHUB_REPOSITORY }}/$file"
            echo S3_BUCKET
            echo $S3_BUCKET
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file"
                aws s3api delete-object --bucket "$S3_BUCKET" --key "$S3_PATH"
            done