name: CI

on:
  push:
    branches:
      - master
env:
  NEW_FILENAME: "lambda_function.py"

jobs:
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: 只下载更新的文件
        uses: actions/checkout@v3

      - name: 配置AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: 所有改变的文件
        run: |
          echo "Actor: ${{ toJson(steps) }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done
          mkdir aaa

      - name: all_modified_files的文件
        run: |
            for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
                echo "$file" >> origin_all_modified_files.txt
                mv $file aaa/
                filename=$(basename "$file")
                echo "$filename" >> abs_all_modified_files.txt
                if [[ $filename == *.py ]]; then
                  echo "The file $filename is in .py format."
                  filename_replace=$(echo "$filename" | sed 's/\.py$//')
                  response=$(aws lambda get-function --function-name "$filename_replace" --output json)
                  # 判断返回的 JSON 是否包含有效的函数信息
                  if [ -n "$(echo "$response" | jq '.Configuration')" ]; then
                    # 提取 FunctionArn 字段的值
                    functionArn=$(echo "$response" | jq -r '.Configuration.FunctionArn')
                    # 检查 FunctionArn 是否不为空
                    if [ -n "$functionArn" ]; then
                      echo "Lambda 函数存在"
                          # 更新 Lambda 函数代码
                          cd aaa
                          mv $filename lambda_function.py
                          zip -r code.zip lambda_function.py
                          aws lambda update-function-code --function-name "$functionArn" --zip-file fileb://aaa/code.zip
                          rm code.zip lambda_function.py
                          cd ..
                    else
                      echo "Lambda 函数不存在"
                    fi
                  else
                    echo "无效的 JSON 返回"
                  fi
                else
                  echo "The file $filename is not in .py format."
                fi
            done
          
            cat origin_all_modified_files.txt
            echo "------"
            cat abs_all_modified_files.txt
            echo "------"
            ls -1 aaa

      - name: deleted_files的文件
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file" >> origin_deleted_files.txt
                filename=$(basename "$file")
                echo "$filename" >> abs_deleted_files.txt
            done
            cat origin_deleted_files.txt
            echo "------"
            cat abs_deleted_files.txt

                 # rm aaa/$filename
