name: CI

on:
  push:
    branches:
      - master

env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: 检查架构

        run: |
          echo $GITHUB_REPOSITORY
          echo $BUCKET_NAME
      - name: 只下载更新的文件
        uses: actions/checkout@v3

      - name: 配置AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 打印输出All修改
        id: changed-files
        uses: tj-actions/changed-files@v37
        run: |
          echo "Actor: ${{ toJson(steps) }}"

      - name: List and Upload All Change Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"          
            REMOTE_PATH="s3://$BUCKET_NAME/$GITHUB_REPOSITORY/$file"
            aws s3 cp $file $REMOTE_PATH
          done

      - name:  List and Delete All Deleted Files
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file"
                S3_PATH="$GITHUB_REPOSITORY/$file"
                aws s3api delete-object --bucket $BUCKET_NAME --key $S3_PATH
            done