name: Get New File Name

on:
  push:
    branches:
      - master

jobs:
  get-file-name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get diff of commits
      id: diff
      run: echo "::set-output name=diff::$(git diff --name-only HEAD^..HEAD)"
      
    - name: Extract new file name
      id: extract-file-name
      run: |
        echo "${{ steps.diff.outputs.diff }}" | while read -r line; do
          if [[ $line =~ ^\+([^/]*)/ ]]; then
            echo "::set-output name=file_name::${BASH_REMATCH[1]}"
          fi
        done
      
    - name: Print new file name
      run: echo "New file name: ${{ steps.extract-file-name.outputs.file_name }}"
