name: CI

on:
  push:
    branches:
      - master
env:
  NEW_FILENAME: "lambda_function.py"

jobs:
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: 只下载更新的文件
        uses: actions/checkout@v3

      - name: 配置AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Change Files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: List All Change Files
        run: |
          echo "Actor: ${{ toJson(steps) }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done
          mkdir aaa
      - name: Run a step if my-file.txt was modified
        if: contains(steps.changed-files.outputs.modified_files, 'my-file.txt')
        run: |
          echo "my-file.txt file has been modified."

      - name: deleted_files的文件
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file" >> origin_deleted_files.txt
                filename=$(basename "$file")
                echo "$filename" >> abs_deleted_files.txt
            done
            cat origin_deleted_files.txt
            echo "------"
            cat abs_deleted_files.txt

                 # rm aaa/$filename
