on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get file changes
        id: file_changes
        run: |
          echo ::set-output name=added_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '.*')
          echo ::set-output name=deleted_files::$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -E '.*')
          echo ::set-output name=modified_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '.*')

      - name: Print file changes
        run: |
          echo "Added files: ${{ steps.file_changes.outputs.added_files }}"
          echo "Deleted files: ${{ steps.file_changes.outputs.deleted_files }}"
          echo "Modified files: ${{ steps.file_changes.outputs.modified_files }}"
