name: CI

on:
  push:
    branches:
      - master
      
jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - name: Display event information
        run: |
          echo "Webhook event name: ${{ github.event_name }}"
          echo "event is: ${{ toJson(github) }}"
