name: CI

on:
  push:
    branches:
      - master
env:
  NEW_FILENAME: "lambda_function.py"

jobs:
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: 只下载更新的文件
        uses: actions/checkout@v3

      - name: 配置AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get changed files and write the outputs to a json file
        id: changed-files-write-output-files-json
        uses: ./
        with:
          json: true
          write_output_files: true
      - name: Verify the contents of the .github/outputs/added_files.json file
        run: |
          cat .github/outputs/added_files.json

      - name: Get Change Files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: List All Change Files
        run: |
          echo "Actor: ${{ toJson(steps) }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
            aws s3 cp $file s3://lq-open/$file
          done
          mkdir aaa

      - name:  List adn Delete All deleted_files
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file"
                aws s3api delete-object --bucket lq-open --key $file
            done

      - name: 列出Delete Files
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file"
                filename=$(basename "$file")
                echo "$filename"
            done

      - name: deleted_files的文件
        run: |
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file" >> origin_deleted_files.txt
                filename=$(basename "$file")
                echo "$filename" >> abs_deleted_files.txt
            done
            cat origin_deleted_files.txt
            echo "------"
            cat abs_deleted_files.txt

                 # rm aaa/$filename
