name: CI

on:
  push:
    branches:
      - master
      
jobs:
  bar:
    runs-on: ["ubuntu-latest"]
    steps:
      - run: echo "event name is:" ${{ github }} 
      - run: echo "event type is:" ${{ github.event.action }} 
