name: Get Push Changes
on:
  push:
    branches:
      - master

jobs:
  get_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Push Changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | awk '/^[A|D|M]/ {print $2}')
          NEW_FILES=$(git diff --name-only HEAD^ HEAD | awk '/^[A]/ {print $2}')
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD | awk '/^[M]/ {print $2}')
          DELETED_FILES=$(git diff --name-only HEAD^ HEAD | awk '/^[D]/ {print $2}')

          echo "Changed files:"
          echo "$CHANGED_FILES"

          echo "New files:"
          echo "$NEW_FILES"

          echo "Modified files:"
          echo "$MODIFIED_FILES"

          echo "Deleted files:"
          echo "$DELETED_FILES"

