name: CI

on:
  push:
    branches:
      - master
      
jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - name: Display event information
        run: |
          echo "event name is: ${{ github.event_name }}"
          echo "event type is: ${{ github.event }}"
          echo "event is: ${{ toJson(github.event) }}"
